import Link from "@/node_modules/next/link";
import "./global.css";
import { Inter } from "next/font/google";
import { userService } from "./components/users/user.service";
import logOut from "./components/header/actions";
import Header from "./components/header/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black dark:bg-neutral-800  text-white max-w-screen-sm mx-auto`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
